#!/usr/bin/env bash
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PRIMITIVE_IMAGE=${PRIMITIVE_IMAGE:="$(awk -F '[ :]' '{print $2}' "${_DIR}/Dockerfile")"}
export PRIMITIVE_IMAGE_VERSION=${PRIMITIVE_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' "${_DIR}/Dockerfile")"}
export PRIMITIVE_ROOT=${PRIMITIVE_ROOT:="$DOKKU_LIB_ROOT/services/primitive"}
export DOKKU_LIB_HOST_ROOT=${DOKKU_LIB_HOST_ROOT:=$DOKKU_LIB_ROOT}
export PRIMITIVE_HOST_ROOT=${PRIMITIVE_HOST_ROOT:="$DOKKU_LIB_HOST_ROOT/services/primitive"}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "connect" "export" "import")
export PLUGIN_COMMAND_PREFIX="primitive"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$PRIMITIVE_ROOT
export PLUGIN_DATA_HOST_ROOT=$PRIMITIVE_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(8000)
export PLUGIN_DATASTORE_WAIT_PORT=8000
export PLUGIN_DEFAULT_ALIAS="PRIMITIVE"
export PLUGIN_DISABLE_PULL=${PRIMITIVE_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="PRIMITIVE_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_PRIMITIVE"
export PLUGIN_IMAGE=$PRIMITIVE_IMAGE
export PLUGIN_IMAGE_VERSION=$PRIMITIVE_IMAGE_VERSION
export PLUGIN_SCHEME="http"
export PLUGIN_SERVICE="Primitive"
export PLUGIN_VARIABLE="PRIMITIVE"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="data"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.34.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.5.0"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.14.0"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.6.0"

export PRIMITIVE_CONFIG_OPTIONS=${PRIMITIVE_CONFIG_OPTIONS:=""}
